name: Deploy .NET Microservices

on:
  push:
    branches:
      - master

env:
  IMAGE_PREFIX: briankimurgor/portfoliorepo
  COMPOSE_PROJECT_NAME: portfolio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t $IMAGE_PREFIX-auth:latest ./api/AuthService
          docker build -t $IMAGE_PREFIX-badge:latest ./api/BadgeService
          docker build -t $IMAGE_PREFIX-blog:latest ./api/BlogService
          docker build -t $IMAGE_PREFIX-profile:latest ./api/ProfileService
          docker build -t $IMAGE_PREFIX-project:latest ./api/ProjectService
          docker build -t $IMAGE_PREFIX-social:latest ./api/SocialService
          docker build -t $IMAGE_PREFIX-work:latest ./api/WorkService




      - name: Push images to Docker Hub
        run: |
          docker push $IMAGE_PREFIX-auth:latest
          docker push $IMAGE_PREFIX-badge:latest
          docker push $IMAGE_PREFIX-blog:latest
          docker push $IMAGE_PREFIX-profile:latest
          docker push $IMAGE_PREFIX-project:latest
          docker push $IMAGE_PREFIX-social:latest
          docker push $IMAGE_PREFIX-work:latest


