name: Deploy .NET Microservices

on:
  push:
    branches:
      - master

env:
  IMAGE_PREFIX: briankimurgor/portfoliorepo
  COMPOSE_PROJECT_NAME: portfolio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -t $IMAGE_PREFIX-auth:latest ./api/AuthService

      - name: Push images to Docker Hub
        run: |
          docker push $IMAGE_PREFIX-auth:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            docker pull $IMAGE_PREFIX-auth:latest

            cd /var/www/microservices
            docker-compose down
            docker-compose up -d --remove-orphans
        env:
          IMAGE_PREFIX: ${{ env.IMAGE_PREFIX }}
